openapi: 3.0.1
info:
  title: Aggregator API
  description: API for aggregating air quality stations from GIOS and OpenAQ.
  version: "1.0.0"
servers:
  - url: /aggregator
paths:
  /stations:
    get:
      summary: Get all stations
      description: Returns a list of all air quality stations from all sources.
      operationId: getAllStations
      responses:
        '200':
          description: List of stations
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/StationWrapperDTO'
components:
  schemas:
    StationWrapperDTO:
      type: object
      properties:
        id:
          type: string
          example: "12345"
        name:
          type: string
          example: "Warszawa - Marszałkowska"
        location:
          type: string
          example: "Marszałkowska 100, Warszawa"
        gegrLat:
          type: number
          format: double
          example: 52.2297
        gegrLon:
          type: number
          format: double
          example: 21.0122
        lastUpdated:
          type: string
          format: date-time
          example: "2024-01-15T10:00:00"
        parameters:
          type: array
          items:
            $ref: "#/components/schemas/ParameterWrapperDTO"

    ParameterWrapperDTO:
      type: object
      properties:
        id:
          type: string
          example: "PM10"
        name:
          type: string
          example: "pył zawieszony PM10"
        unit:
          type: string
          example: "µg/m³"
        description:
          type: string
          example: "Stężenie pyłu zawieszonego PM10"