openapi: 3.0.3
info:
  title: Air Quality Aggregation API
  version: 1.0.0
  description: API returning aggregated air quality parameter data for a given voivodeship.
servers:
  - url: /aggregator
paths:
  /airQuality/{voivodeship}:
    get:
      summary: Get aggregated air quality data for a voivodeship
      parameters:
        - in: path
          name: voivodeship
          required: true
          schema:
            $ref: '#/components/schemas/Voivodeship'
          description: Name of the voivodeship (province) for which to fetch air quality data.
      responses:
        '200':
          description: List of aggregated air quality parameters
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AggregatedVoivodeshipData'
        '404':
          description: No data found for the given voivodeship

components:
  schemas:
    AggregatedVoivodeshipData:
      type: object
      properties:
        voivodeship:
          $ref: '#/components/schemas/Voivodeship'
        parameters:
          type: array
          items:
            $ref: '#/components/schemas/Parameter'

    Parameter:
      type: object
      properties:
        id:
          type: string
          example: "PM10"
        name:
          type: string
          example: "pyl zawieszony PM10"
        unit:
          type: string
          example: "µg/m³"
        description:
          type: string
          example: "Stezenie pylu zawieszonego PM10"

    Voivodeship:
      type: string
      description: Name of the voivodeship (province)
      enum:
        - DOLNOSLASKIE
        - KUJAWSKO_POMORSKIE
        - LUBELSKIE
        - LUBUSKIE
        - LODZKIE
        - MALOPOLSKIE
        - MAZOWIECKIE
        - OPOLSKIE
        - PODKARPACKIE
        - PODLASKIE
        - POMORSKIE
        - SLASKIE
        - SWIETOKRZYSKIE
        - WARMINSKO_MAZURSKIE
        - WIELKOPOLSKIE
        - ZACHODNIOPOMORSKIE
