openapi: 3.0.1
info:
  title: OpenAQ API
  contact: {}
  version: 1.0.0
servers:
  - url: http://openaq-data:3000/
paths:
  /stations:
    get:
      tags:
        - stations
      summary: Get all stations
      description: Returns a list of all stations
      operationId: getStations
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                additionalProperties:
                  type: array
                  items:
                    $ref: '#/components/schemas/internal.Station'
  /stations/{id}:
    get:
      tags:
        - stations
      summary: Get station by ID
      description: Returns a station by its ID
      operationId: getStationById
      parameters:
        - name: id
          in: path
          description: Station ID
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                additionalProperties:
                  $ref: '#/components/schemas/internal.Station'
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                additionalProperties:
                  type: string
  /stations/{id}/measurements:
    get:
      tags:
        - measurements
      summary: Get latest measurements by station
      description: Returns the latest measurement for each parameter at a specific
        station
      operationId: getMeasurementsByStation
      parameters:
        - name: id
          in: path
          description: Station ID
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                additionalProperties:
                  type: array
                  items:
                    $ref: '#/components/schemas/internal.Measurement'
  /stations/{id}/parameters:
    get:
      tags:
        - parameters
      summary: Get parameters by station
      description: Returns parameters for a specific station
      operationId: getParametersByStation
      parameters:
        - name: id
          in: path
          description: Station ID
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                additionalProperties:
                  type: array
                  items:
                    $ref: '#/components/schemas/internal.Parameter'
components:
  schemas:
    internal.Coordinates:
      type: object
      properties:
        latitude:
          type: number
        longitude:
          type: number
    internal.Country:
      type: object
      properties:
        code:
          type: string
        id:
          type: integer
        name:
          type: string
    internal.Measurement:
      type: object
      properties:
        coordinates:
          $ref: '#/components/schemas/internal.Coordinates'
        datetime:
          $ref: '#/components/schemas/internal.MeasurementDateTime'
        sensorId:
          type: integer
        stationId:
          type: integer
        value:
          type: number
    internal.MeasurementDateTime:
      type: object
      properties:
        local:
          type: string
        utc:
          type: string
    internal.Parameter:
      type: object
      properties:
        displayName:
          type: string
        id:
          type: integer
        name:
          type: string
        units:
          type: string
    internal.Station:
      type: object
      properties:
        country:
          $ref: '#/components/schemas/internal.Country'
        id:
          type: integer
        locality:
          type: string
        name:
          type: string
        parameters:
          type: array
          items:
            $ref: '#/components/schemas/internal.Parameter'
        timezone:
          type: string
x-original-swagger-version: "2.0"
