server {
    listen 80;

    location /aggregatedData {
        proxy_pass http://aggregator-app:8082;
    }

    location / {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;
    }
}
