// Package types provides primitives to interact with the openapi HTTP API.
//
// Code generated by unknown module path version unknown version DO NOT EDIT.
package types

import (
	"time"
)

// Measurement defines model for Measurement.
type Measurement struct {
	ParameterId int32     `json:"parameterId"`
	StationId   int32     `json:"stationId"`
	Timestamp   time.Time `json:"timestamp"`
	Value       float64   `json:"value"`
}

// Parameter defines model for Parameter.
type Parameter struct {
	Description *string `json:"description,omitempty"`
	DisplayName string  `json:"displayName"`
	Id          int32   `json:"id"`
	Name        string  `json:"name"`
	Units       string  `json:"units"`
}

// Station defines model for Station.
type Station struct {
	Id           int32   `json:"id"`
	Latitude     float64 `json:"latitude"`
	Locality     string  `json:"locality"`
	Longitude    float64 `json:"longitude"`
	Name         string  `json:"name"`
	ParameterIds []int32 `json:"parameterIds"`
	Timezone     string  `json:"timezone"`
}
